CREATE DATABASE IF NOT EXISTS `rent_ai_suport` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `rent_ai_suport`;

DROP TABLE IF EXISTS `password_resets`;
DROP TABLE IF EXISTS `login_sessions`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `settings`;

CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `role` ENUM('customer', 'admin', 'support', 'super_admin') NOT NULL DEFAULT 'customer',
  `balance` DECIMAL(15, 4) NOT NULL DEFAULT 0.0000,
  `avatar` VARCHAR(500) DEFAULT NULL,
  `phone` VARCHAR(50) DEFAULT NULL,
  `telegram_contact` VARCHAR(100) DEFAULT NULL,
  `timezone` VARCHAR(100) DEFAULT 'Asia/Ho_Chi_Minh (GMT+7)',
  `language` VARCHAR(10) NOT NULL DEFAULT 'en',
  `currency` VARCHAR(10) NOT NULL DEFAULT 'USD',
  `two_factor_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `two_factor_secret` VARCHAR(100) DEFAULT NULL,
  `api_key` VARCHAR(128) DEFAULT NULL,
  `email_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('active', 'banned', 'suspended') NOT NULL DEFAULT 'active',
  `last_login_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_username` (`username`),
  UNIQUE KEY `uk_users_email` (`email`),
  UNIQUE KEY `uk_users_phone` (`phone`),
  UNIQUE KEY `uk_users_api_key` (`api_key`),
  KEY `idx_users_role` (`role`),
  KEY `idx_users_status` (`status`),
  KEY `idx_users_created_at` (`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `password_resets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` TIMESTAMP NOT NULL,
  `used` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_password_resets_token` (`token`),
  KEY `idx_password_resets_email` (`email`),
  KEY `idx_password_resets_expires` (`expires_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `login_sessions` (
  `id` VARCHAR(191) NOT NULL,
  `user_id` INT NOT NULL,
  `token_hash` CHAR(64) NOT NULL,
  `user_agent` VARCHAR(500) DEFAULT NULL,
  `ip_address` VARCHAR(100) DEFAULT NULL,
  `location` VARCHAR(255) DEFAULT NULL,
  `last_active_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `revoked_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_login_sessions_token_hash` (`token_hash`),
  KEY `idx_login_sessions_user` (`user_id`, `revoked_at`, `expires_at`),
  CONSTRAINT `fk_login_sessions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `default_language` VARCHAR(10) NOT NULL DEFAULT 'en',
  `default_currency` VARCHAR(10) NOT NULL DEFAULT 'USD',
  `site_name` VARCHAR(255) NOT NULL DEFAULT 'NexusSMM Enterprise',
  `site_tagline` VARCHAR(255) DEFAULT NULL,
  `site_logo_url` VARCHAR(500) DEFAULT NULL,
  `favicon_url` VARCHAR(500) DEFAULT NULL,
  `primary_brand_color` VARCHAR(50) DEFAULT '#2563eb',
  `support_email` VARCHAR(255) DEFAULT 'support@nexussmm.io',
  `support_telegram` VARCHAR(100) DEFAULT '@NexusSMM_SupportBot',
  `support_hotline` VARCHAR(50) DEFAULT '+84 (0) 988 889 999',
  `smtp_host` VARCHAR(255) DEFAULT NULL,
  `smtp_port` INT DEFAULT 587,
  `smtp_username` VARCHAR(255) DEFAULT NULL,
  `smtp_password` VARCHAR(255) DEFAULT NULL,
  `smtp_encryption` ENUM('tls', 'ssl', 'none') DEFAULT 'tls',
  `smtp_from_email` VARCHAR(255) DEFAULT NULL,
  `smtp_from_name` VARCHAR(255) DEFAULT NULL,
  `allow_user_registration` TINYINT(1) NOT NULL DEFAULT 1,
  `allow_free_trial_panel` TINYINT(1) NOT NULL DEFAULT 1,
  `allow_guest_service_viewing` TINYINT(1) NOT NULL DEFAULT 1,
  `enable_live_chat_widget` TINYINT(1) NOT NULL DEFAULT 1,
  `header_announcement_bar` TEXT DEFAULT NULL,
  `header_announcement_active` TINYINT(1) NOT NULL DEFAULT 1,
  `footer_copyright` VARCHAR(500) DEFAULT NULL,
  `seo_meta_title` VARCHAR(255) DEFAULT NULL,
  `seo_meta_keywords` TEXT DEFAULT NULL,
  `seo_meta_description` TEXT DEFAULT NULL,
  `custom_css` TEXT DEFAULT NULL,
  `custom_header_scripts` TEXT DEFAULT NULL,
  `maintenance_mode` TINYINT(1) NOT NULL DEFAULT 0,
  `auto_dispatch_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `auto_provisioning_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `auto_banking_sync` TINYINT(1) NOT NULL DEFAULT 1,
  `usd_to_vnd_rate` DECIMAL(12, 2) NOT NULL DEFAULT 25400.00,
  `min_deposit_usd` DECIMAL(10, 2) NOT NULL DEFAULT 5.00,
  `vietqr_bank_code` VARCHAR(50) DEFAULT 'MBBANK',
  `vietqr_account_number` VARCHAR(50) DEFAULT '0988889999',
  `vietqr_account_holder` VARCHAR(255) DEFAULT 'NEXUS SMM HOLDINGS',
  `vietqr_auto_verify` TINYINT(1) NOT NULL DEFAULT 1,
  `usdt_trc20_address` VARCHAR(100) DEFAULT NULL,
  `usdt_erc20_address` VARCHAR(100) DEFAULT NULL,
  `crypto_auto_confirm_blocks` INT NOT NULL DEFAULT 3,
  `sync_interval` INT NOT NULL DEFAULT 3,
  `auto_refund_on_error` TINYINT(1) NOT NULL DEFAULT 1,
  `low_balance_alert_threshold` DECIMAL(10, 2) NOT NULL DEFAULT 50.00,
  `default_profit_margin` DECIMAL(5, 2) NOT NULL DEFAULT 25.00,
  `auto_retry_stalled_orders` TINYINT(1) NOT NULL DEFAULT 1,
  `filter_sensitive_keywords` TINYINT(1) NOT NULL DEFAULT 1,
  `webhook_url` VARCHAR(500) DEFAULT NULL,
  `webhook_secret` VARCHAR(255) DEFAULT NULL,
  `gemini_model` VARCHAR(100) DEFAULT 'gemini-2.5-flash',
  `system_prompt` TEXT DEFAULT NULL,
  `auto_ticket_reply_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `auto_dns_diagnostic` TINYINT(1) NOT NULL DEFAULT 1,
  `auto_margin_optimizer` TINYINT(1) NOT NULL DEFAULT 1,
  `max_daily_ai_tokens` INT NOT NULL DEFAULT 500000,
  `temperature` DECIMAL(3, 2) NOT NULL DEFAULT 0.70,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
